model:
  base_learning_rate: 3.24e-06
  target: hrig.models.hrig.HRIGTransformer
  params:
    first_stage_key: image_gt
    cond_stage_key: image
    mask_key: mask
    
    transformer_config:
      target: asset.modules.transformer.asset.ASSET
      params:
        vocab_size: 256
        d_model: 512
        max_position_embeddings: 256
        attention_dropout: 0.0
        dropout: 0.0
        encoder_layers: 7
        decoder_layers: 15
        encoder_ffn_dim: 1024
        decoder_ffn_dim: 1024
        PEG_list: ['E_all', 'D_0']
        PEG_ks: 5
        block_h: 16
        block_w: 4

    first_stage_config:
      target: asset.models.vqgan.VQModel
      params:
        embed_dim: 4
        n_embed: 256
        ckpt_path: models/first_stage_models/vq-f8-n256/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__
  
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    # wrap: false
    train:
      target: hrig.data.rain.RainBase
      params:
        data_root: /home/zhoukaibin/data/lane/images
        json_file: /home/zhoukaibin/data/lane/trainset.json
        size: 256
    validation:
      target: hrig.data.rain.RainBase
      params:
        data_root: /home/zhoukaibin/data/lane/images
        json_file: /home/zhoukaibin/data/lane/testset.json
        size: 256


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True