data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 4
    validation:
      target: hrig_blender.data.rainReal.RainBlenderReal
      params:
        data_root: /home/zhoukaibin/data/dataset/RealBGMask/R100H_rain512_randomRain_ratio2
        json_file: /home/zhoukaibin/data/dataset/RealBGMask/R100H_rain512_randomRain_ratio2/dataset.json
        size: 512
        readImg: true
