model:
  base_learning_rate: 4.5e-6
  target: asset.models.vqgan.VQModel
  params:
    image_key: image_gt
    embed_dim: 256
    n_embed: 1024
    legacy: True
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
      conv_type: PartialConv
      downsample_legacy: False
      norm_type: RegionNorm
    lossconfig:
      target: asset.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: hrig.data.rain.RainBase
      params:
        data_root: /home/zhoukaibin/data/dataset/hri
        json_file: /home/zhoukaibin/data/dataset/hri/trainset.json
        size: 256
    validation:
      target: hrig.data.rain.RainBase
      params:
        data_root: /home/zhoukaibin/data/dataset/hri
        json_file: /home/zhoukaibin/data/dataset/hri/testset.json
        size: 256