the_seed: 64

config_path: /home/zhoukaibin/data/Code/HRIG/configs/asset/hri-asset-guiding-transformer-hw256.yaml
ckpt_path: /home/zhoukaibin/data/Code/HRIG/logs/2023-03-29T16-59-06_hri-asset-guiding-transformer-hw256/checkpoints/epoch=000007.ckpt

NUMBER_BATCHES: 1
NUMBER_SAMPLES: 1

temperature: 1.0
top_k: 100