model:
  base_learning_rate: 2.0e-06
  target: hrig_blender.models.hrig.GuidingDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: rainy_image
    cond_stage_key: masked_background
    image_size: 64
    channels: 3
    monitor: val/loss_gdm_simple_ema
    cond_stage_trainable: false
    conditioning_key: concat

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    # wrap: false
    train:
      target: hrig_blender.data.rain.RainBlender
      params:
        data_root: /home/ubuntu/data/BlenderRain
        json_file: /home/ubuntu/data/BlenderRain/trainset.json
        size: 256
        useDepth: false
    validation:
      target: hrig_blender.data.rain.RainBlender
      params:
        data_root: /home/ubuntu/data/BlenderRain
        json_file: /home/ubuntu/data/BlenderRain/testset.json
        size: 256
        useDepth: false


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_epochs: 100